### ISSUE TITLE
Chicken Dinner on new map Deston not recognised on events/presence

### ISSUE THREAD

**Issue by chlctt** [PTRFRLL/dinnerbot#62]
I added the new map Deston last week via push request #60.

Unfortunately, wins on new map Deston aren't recognised via player presence.

I am not sure, what might be the point here.

This is what the dinnerbot recognises for wins on Miramar. But this doesn't work on Deston.

```
Jul-19-2022 19:31:30 [info]:[events/presence]: Win detected by presence, pre-exclude: Winner Winner Chicken Dinner!, Miramar, 2/84

Jul-19-2022 19:31:30 [info]:[events/presence]: Spectator win detected via presence for XXX, adding to spectators

Jul-19-2022 19:31:30 [info]:[events/presence]: Not found in winners map, adding XXX

Jul-19-2022 19:31:41 [info]:[events/presence]: Post win for XXX: [Winner Winner Chicken Dinner!, Miramar, 2/84] => [In Lobby]
```

**Comment by chlctt** [comment]
I just found out that games running Deston have the matchType "seasonal".

```
{
  "data": {
    "type": "match",
    "id": "c7da28e3-10b1-4e03-b7af-483897e9c5b1",
    "attributes": {
      "gameMode": "squad-fpp",
      "titleId": "bluehole-pubg",
      "shardId": "steam",
      "tags": null,
      "isCustomMatch": false,
      "createdAt": "2022-07-17T14:40:29Z",
      "duration": 1674,
      "matchType": "seasonal",
      "seasonState": "progress",
      "stats": null,
      "mapName": "Kiki_Main"
    },
```

In pubg.js it is limited to 'offical' and I'm not sure, why it was chosen.

[In lib/pubg.js](https://github.com/PTRFRLL/dinnerbot/blob/42f5a5452bf706bb1b77f45aa8ea668eac1958ce/lib/pubg.js#L90)

**Comment by chlctt** [comment]
Looking at the PUBG API documentation, following values are piss

`airoyale, arcade, custom, event, official, seasonal, training`

From my point of view, it would make sense to add 'seasonal' as additional option.

**Comment by PTRFRLL** [comment]
I did this to filter out getting false positive wins on things like custom and arcade game (TDM) modes. At the time, I don't think `seasonal` was an option. We can add that to `getLatestWin` but that won't fix the presence detection for Deston as presence detection doesn't rely on that method to check for a win, just the `VALID_MAPS` constant. 

I think the issue here is PUBG hasn't updated the game to report presence to Steam/Discord. If you look at a user's Discord presence when they play Deston, it just says `Playing` instead of `Playing, 34/100, Deston` (or something like that). I've seen this happen with other new maps, they usually add it in a later patch.

**Comment by chlctt** [comment]
After including Deston to standard map cycle, removing it as standalone map option, Steam is now showing Deston correctly in the players's status.

I think Steam and/or Discord actually might have the problem with the matchType, which is not included in status.

For me the issue is closed.
